/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Kontakt = {
  _id: string;
  _type: "kontakt";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  adresse: string;
  postnummer: string;
  poststed: string;
  telefon: string;
  epost: string;
  apningstiderMandag?: string;
  apningstiderTirsdag?: string;
  apningstiderOnsdag?: string;
  apningstiderTorsdag?: string;
  apningstiderFredag?: string;
  apningstiderLordag?: string;
  apningstiderSondag?: string;
};

export type Priser = {
  _id: string;
  _type: "priser";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  linjer?: Array<{
    behandling: string;
    pris: number;
    varighet?: string;
    _type: "prislinje";
    _key: string;
  }>;
  merknad?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Behandler = {
  _id: string;
  _type: "behandler";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  navn: string;
  tittel: string;
  bilde?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  beskrivelse?: string;
  rekkefolge: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Innstillinger = {
  _id: string;
  _type: "innstillinger";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  klinikknavn: string;
  bookingUrl: string;
  bookingTekst: string;
  hovedbilde?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  omStedet?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet";
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | Kontakt
  | Priser
  | SanityImageAssetReference
  | Behandler
  | SanityImageCrop
  | SanityImageHotspot
  | Innstillinger
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: ../klinikk-web/sanity/queries.ts
// Variable: LAYOUT_INNSTILLINGER_QUERY
// Query: *[_type == "innstillinger"][0]{    klinikknavn, bookingUrl, bookingTekst  }
export type LAYOUT_INNSTILLINGER_QUERY_RESULT = {
  klinikknavn: string;
  bookingUrl: string;
  bookingTekst: string;
} | null;

// Source: ../klinikk-web/sanity/queries.ts
// Variable: FORSIDE_QUERY
// Query: *[_type == "innstillinger"][0]{    klinikknavn, omStedet, hovedbilde  }
export type FORSIDE_QUERY_RESULT = {
  klinikknavn: string;
  omStedet: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet";
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  hovedbilde: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
} | null;

// Source: ../klinikk-web/sanity/queries.ts
// Variable: BEHANDLERE_QUERY
// Query: *[_type == "behandler"] | order(rekkefolge asc){    _id, navn, tittel, beskrivelse, bilde  }
export type BEHANDLERE_QUERY_RESULT = Array<{
  _id: string;
  navn: string;
  tittel: string;
  beskrivelse: string | null;
  bilde: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
}>;

// Source: ../klinikk-web/sanity/queries.ts
// Variable: PRISER_QUERY
// Query: *[_type == "priser"][0]{    linjer[]{ _key, behandling, pris, varighet },    merknad  }
export type PRISER_QUERY_RESULT = {
  linjer: Array<{
    _key: string;
    behandling: string;
    pris: number;
    varighet: string | null;
  }> | null;
  merknad: string | null;
} | null;

// Source: ../klinikk-web/sanity/queries.ts
// Variable: KONTAKT_QUERY
// Query: *[_type == "kontakt"][0]{    adresse, postnummer, poststed, telefon, epost,    apningstiderMandag, apningstiderTirsdag, apningstiderOnsdag,    apningstiderTorsdag, apningstiderFredag, apningstiderLordag,    apningstiderSondag  }
export type KONTAKT_QUERY_RESULT = {
  adresse: string;
  postnummer: string;
  poststed: string;
  telefon: string;
  epost: string;
  apningstiderMandag: string | null;
  apningstiderTirsdag: string | null;
  apningstiderOnsdag: string | null;
  apningstiderTorsdag: string | null;
  apningstiderFredag: string | null;
  apningstiderLordag: string | null;
  apningstiderSondag: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "innstillinger"][0]{\n    klinikknavn, bookingUrl, bookingTekst\n  }\n': LAYOUT_INNSTILLINGER_QUERY_RESULT;
    '\n  *[_type == "innstillinger"][0]{\n    klinikknavn, omStedet, hovedbilde\n  }\n': FORSIDE_QUERY_RESULT;
    '\n  *[_type == "behandler"] | order(rekkefolge asc){\n    _id, navn, tittel, beskrivelse, bilde\n  }\n': BEHANDLERE_QUERY_RESULT;
    '\n  *[_type == "priser"][0]{\n    linjer[]{ _key, behandling, pris, varighet },\n    merknad\n  }\n': PRISER_QUERY_RESULT;
    '\n  *[_type == "kontakt"][0]{\n    adresse, postnummer, poststed, telefon, epost,\n    apningstiderMandag, apningstiderTirsdag, apningstiderOnsdag,\n    apningstiderTorsdag, apningstiderFredag, apningstiderLordag,\n    apningstiderSondag\n  }\n': KONTAKT_QUERY_RESULT;
  }
}
